### ISSUE TITLE
TODO Dev

### ISSUE THREAD

**Issue by stefan-st** [stefan-st/FunfairPrototype#1]
- [ ] Materials for disappearing people
- [ ] Pickup Bear animation
- [ ] Game loop: start, pause, restart
- [ ] Optimization
- [ ] Bank scene: be able to shoot the lady
- [ ] Bank scene: update pickup money colliders
- [ ] Be able to take a ride on the different attractions
- [ ] Don't allow the player to fall of the island
- [ ] Make it clear you need to click to shoot
- [ ] Make it clear you need to pick the bear when the timer is done
- [ ] Make the ducks more broken as you shoot them: 3 states
